pastaArquivos = "in\\"
pastaResultados = "out\\"
relacaoCabecalho = {
    "(Polinomial) A":None,
    "(Polinomial) B":None,
    "(Polinomial) C":None,
    "Aceleração da Gravidade (g)":None,
    "Adversa Afogado":None,
    "Adversa Extravasando":None,
    "Adversa Extravasando (LPS)":None,
    "Adversa Jorrante":None,
    "Adversa Parada":None,
    "Adversa Seco":None,
    "Adversa Seco (LPS)":None,
    "Adversa Transbordou":None,
    "Adversa Transbordou (LPS)":None,
    "Altura (cm)":None,
    "Ativo":None,
    "Barômetro Inicial (B0)":None,
    "Base (cm)":None,
    "Base Menor (B)":None,
    "Coeficiente Linear (G)":None,
    "Coeficiente de Calibração (Cf)":None,
    "Coeficiente de Descarga (CD)":None,
    "Coeficiente de Descarga (Cd)":None,
    "Coeficiente de Temperatura (K)":None,
    "Coeficiente termal (Ct)":None,
    "Complexo Mineiro":"Complexo Mineiro",
    "Comprimento da crista (m)":None,
    "Condicao de Instrumento":"Condicao de Instrumento",
    "Condição Adversa JORRANTE":None,
    "Condição Adversa SECO":None,
    "Coordenada Leste Instalação (X)":None,
    "Coordenada Leste Projeto (X)":None,
    "Coordenada Norte Instalação (Y)":None,
    "Coordenada Norte Projeto (Y)":None,
    "Cota Instalação (Z)":None,
    "Cota Referência (C)":None,
    "Cota da Base (m)":"Cota do Fundo (m)",
    "Cota da Base da Célula (m)":"Cota da Base da Célula (m)",
    "Cota da Boca":None,
    "Cota da borda livre de projeto (m)":None,
    "Cota da crista da barragem (m)":"Cota da crista da barragem (m)",
    "Cota da soleira do vertedor (m)":"Cota da soleira do vertedor (m)",
    "Cota de Amortecimento (m)":None,
    "Cota de Projeto (Z)":None,
    "Cota de Referência":None,
    "Cota de Referência (CR)":None,
    "Cota de Topo da Célula (m)":"Cota de Topo da Célula (m)",
    "Cota do Fundo (m)":"Cota do Fundo (m)",
    "Cota do Topo (m)":"Cota do Topo (m)",
    "Código":"Código",
    "Código de Projeto":None,
    "Data de instalação":"Data de instalação",
    "Descrição":"Descrição",
    "Digito Inicial (L0)":None,
    "Digito Inicial (R0)":None,
    "Diâmetro":None,
    "Diâmetro de Revestimento":None,
    "Diâmetro do Tubo":"Diâmetro do Tubo",
    "Diâmetro do Tubo (')":"Diâmetro do Tubo",
    "Diâmetro do Tubo (mm)":"Diâmetro do Tubo",
    "Elevação":"Elevação",
    "Elevação Inicial (L0)":None,
    "Estrutura Geotécnica":"Estrutura Geotécnica",
    "Fabricante":None,
    "Furo de referência":None,
    "Furo de refência":None,
    "Fuso":"Fuso",
    "Fórmula 1":None,
    "Fórmula 2":None,
    "Fórmula 3":None,
    "Latitude (UTM)":"Latitude (UTM)",
    "Leitura Inicial (L0)":None,
    "Leitura Inicial Sensor (L0)":None,
    "Leitura Inicial Temperatura (T0)":None,
    "Leitura Inicial do Sensor Ultrassônico (U0)":None,
    "Leitura inicial barômetro (S0)":None,
    "Local Instalação":"Local Instalação",
    "Meta de Vazão":None,
    "Mina":"Mina",
    "Modelo":None,
    "Modelo Datalogger":None,
    "Modelo de Datalogger":None,
    "Modelo do Datalogger":None,
    "Modelo do Equipamento":None,
    "N° de série":None,
    "N° de série do Datalogger":None,
    "Nº Série":None,
    "Nº Série Datalogger":None,
    "Nº de Série":None,
    "Nº de Série do Datalogger":None,
    "Nº de série":None,
    "Nível Dinâmico":None,
    "Nível Estático":None,
    "Nível de Alerta":"Nível de Alerta",
    "Nível de Alerta Geotecnia (>)":"Nível de Alerta",
    "Nível de Alerta Geotecnia (>) (L/s)":"Nível de Alerta",
    "Nível de Alerta (Maior que)":"Nível de Alerta",
    "Nível de Alerta Geotecnia (>) (Maior que)":"Nível de Alerta",
    "Nível de Alerta Geotecnia (>) (L/s) (Maior que)":"Nível de Alerta",
    "Nível de Alerta Hidrogeologia (<)":None,
    "Nível de Alerta Hidrogeologia (<) (L/s)":None,
    "Nível de Alerta no eixo X":None,
    "Nível de Alerta no eixo Y":None,
    "Nível de Alerta no eixo Z":None,
    "Nível de Alerta no vetor de deslocamento":"Nível de Alerta",
    "Nível de Atenção":"Nível de Atenção",
    "Nível de Emergência":"Nível de Emergência",
    "Nível de Emergência Geotecnia (>)  (L/s)":"Nível de Emergência",
    "Nível de Emergência Geotecnia(>)":"Nível de Emergência",
    "Nível de Alerta no vetor de deslocamento (Maior que)":"Nível de Alerta",
    "Nível de Atenção (Maior que)":"Nível de Atenção",
    "Nível de Emergência (Maior que)":"Nível de Emergência",
    "Nível de Emergência Geotecnia (>)  (L/s) (Maior que)":"Nível de Emergência",
    "Nível de Emergência Geotecnia(>) (Maior que)":"Nível de Emergência",
    "Nível de Emergência Hidrogeologia (<)":None,
    "Nível de Emergência Hidrogeologia (<)  (L/s)":None,
    "Nível de Emergência Hidrogeologia (<) (L/s)":None,
    "Nível de Emergência no eixo X":None,
    "Nível de Emergência no eixo Y":None,
    "Nível de Emergência no eixo Z":None,
    "Nível de Emergência no vetor de deslocamento":"Nível de Emergência",
    "Nível de Emergência no vetor de deslocamento (Maior que)":"Nível de Emergência",
    "Nível de Água":None,
    "Número da Outorga":None,
    "Número de série":None,
    "Observação":"Observação",
    "Profundidade (m)":"Profundidade (m)",
    "Referência de Sondagem":None,
    "Sensor":None,
    "Sistema de Coordenadas":"Sistema de Coordenadas",
    "Sistema de Monitoramento":None,
    "Subtipo de Instrumento":"Subtipo de Instrumento",
    "Tag Pims Barômetro Leitura (B)":None,
    "Tag Pims Coordenada Leste (X)":None,
    "Tag Pims Coordenada Norte (Y)":None,
    "Tag Pims Cota (Z)":None,
    "Tag Pims Data da coleta em campo":None,
    "Tag Pims Digito Leitura (L)":None,
    "Tag Pims Digito Leitura (R)":None,
    "Tag Pims Leitura":None,
    "Tag Pims Leitura (m)":None,
    "Tag Pims Leitura (mm)":None,
    "Tag Pims Leitura Atual Sensor (L)":None,
    "Tag Pims Leitura Atual Temperatura (T)":None,
    "Tag Pims Leitura Direta (MCA)":None,
    "Tag Pims Leitura Direta (m)":None,
    "Tag Pims Leitura Hidrometro":None,
    "Tag Pims Leitura Horímetro":None,
    "Tag Pims Leitura Manual (m)":None,
    "Tag Pims Leitura Vazão":None,
    "Tag Pims Leitura atual barômetro (S)":None,
    "Tag Pims Leitura do Sensor Ultrassônico (U1)":None,
    "Tag Pims Leitura nível (m)":None,
    "Tag Pims Nível Dinâmico":None,
    "Tag Pims Pressão da Bomba":None,
    "Tag Pims Prof. intrumento campo (m)":None,
    "Tag Pims Profundidade de campo (m)":None,
    "Tag Pims Profundidade do NA (Dinâmica)":None,
    "Tag Pims Profundidade do NA (Estática)":None,
    "Tag Pims Resultado da coleta (PPM)":None,
    "Tag Pims Temperatura leitura (T)":None,
    "Tag Pims leitura direta (MCA)":None,
    "Tag Pims Índice Pluviométrico":None,
    "Temperatura Inicial (T0)":None,
    "Tipo de Estrutura":"Tipo de Estrutura",
    "Tipo de Instrumento":"Tipo de Instrumento",
    "Valor de Referência do Recipiente (L)":None,
    "Vazão Específica":None,
    "Vazão de Teste":None,
    "longitude (UTM)":"longitude (UTM)",
    "Ângulo 1 (°)":None,
    "Ângulo 2 (°)":None,
    "Ângulo de Instalação (°)":"Ângulo de Instalação (°)",
    "Ângulo do Medidor de Vazão (A)":None,
    # Adicionado para atualização
    "Nível de Alerta no eixo Y (Maior que)": None,
    "Nível de Emergência no eixo X (Maior que)": None,
    "Nível de Emergência no eixo Z (Maior que)": None,
    "Nível de Emergência no eixo Y (Maior que)": None,
    "Nível de Alerta no eixo Z (Maior que)": None,
    "Nível de Alerta no eixo X (Maior que)": None,
    "Nível de Atenção no vetor deslocamento (Maior que)": "Nível de Atenção",
    "Nível de Atenção no eixo X (Maior que)": None,
    "Nível de Atenção no eixo Y (Maior que)": None,
    "Nível de Atenção no eixo Z (Maior que)": None,
    "Nível de Alerta (Menor que)": None,
    "Nível de Emergência (Menor que)": None,
    "Nível de Atenção (Menor que)": None,
    # Adicionado para atualização
    "Cota do extravasor (Maior que)": None,
    "Cota da crista da barragem (Maior que)": None,
    # Adicionado para atualização
    "Cota de Instalação (m)": None,
    "Largura da Garganta (m)": None,
    "Área da Garganta (m²)": None,
    "Cota da Garganta (m)": None,
    "Área de Seção Convergente (m²)": None,
    "Cota de Seção Convergente (m)": None,
    "Altura": None,
    "Base": None,
    "Coeficiente n": None,
    "Coeficiente K": None,
    # Adicionado para atualização
    "Furo de Referência": None,
    "Comprimento do Cabo": None,
    "Tipo de conversor": None,
    "Estação Nº Serie":None,
    "Datalogger Nº Serie":None
    }